{
 "title": "SPO JAPAN GUILD - Cardano Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\n  height:100%;\n  display:flex;\n  flex-direction:column;\n  justify-content:space-between;\n  align-items:center;\n  padding:16px 0 20px;\n  box-sizing:border-box;\n\">\n\n  <a href=\"https://spojapanguild.net/\" target=\"_blank\">\n    <img\n      src=\"https://raw.githubusercontent.com/kuhito-inc/spojapanguild/main/public/images/brand/sjg-yoko-white-logo.png\n\"\n      width=\"250\"\n      alt=\"SPO JAPAN GUILD\">\n  </a>\n\n  <a\n    href=\"https://docs.spojapanguild.net/\"\n    target=\"_blank\"\n    style=\"\n      display:block;\n      text-align:center;\n      text-decoration:none;\n      font-size:20px;\n      font-weight:600;\n      line-height:1.45;\n    \">\n    SPO JAPAN GUILD<br>\n    ドキュメント\n  </a>\n\n  <div\n    style=\"\n      margin-bottom:12px;\n      font-size:13px;\n      color:#6B7280;\n      letter-spacing:0.2px;\n    \">\n    Built with\n    <a\n      href=\"https://kuhito.co.jp\"\n      target=\"_blank\"\n      style=\"\n        color:#FFFFFF;\n        text-decoration:none;\n        font-weight:400;\n      \">\n      Kuhito\n    </a>\n  </div>\n\n</div>"
   }
  },
  {
   "title": "現在のエポック",
   "type": "stat",
   "description": "現在のエポック",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance=\"localhost:12808\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "経過日数",
   "type": "stat",
   "description": "そのエポックが始まってからの経過日数。",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{instance=\"localhost:12808\"}/1440/60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ブロック生成",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "トータルブロック生成数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "block_count", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "KES残り日数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "KES変更タイミング",
   "type": "stat",
   "description": "(startKesPeriod)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{instance=\"localhost:12808\"} / 129600",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "キーローテーション",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "現在のKES"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "KESの有効期限"
    },
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int - cardano_node_metrics_operationalCertificateStartKESPeriod_int + cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "KESの整合性"
    },
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "残KES"
    }
   ]
  },
  {
   "title": "最新カウンター番号",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "op_cert_counter", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "処理されたトランザクション",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ティッカー",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "meta_json.ticker", "text": "", "type": "string" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "1秒以内、ダウンロードされたブロックの概算値",
   "type": "stat",
   "description": "■ブロックの伝搬について：1秒以内にブロックをダウンロードできたおおよその推定値。※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "3秒以内、ダウンロードされたブロックの概算値",
   "type": "stat",
   "description": "■ブロックの伝搬について：3秒以内にブロックをダウンロードできたおおよその推定値。95%のブロックを3秒以内にダウンロードしていれば、よく稼働しているノード指標となります。※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "5秒以内、ダウンロードされたブロックの概算値",
   "type": "stat",
   "description": "■ブロックの伝搬について：5秒以内にブロックをダウンロードできたおおよその推定値。95%のブロックを5秒以内にダウンロードすることは、ウロボロスPraosのセキュリティ上の最低ラインとなります。※ノードを再起動すると初期化されますので適正値になるまで時間がかかります。",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "到着ブロックの追跡(5秒以上)",
   "type": "stat",
   "description": "■5秒以上後に到着したブロックの追跡：ミントされたはずのブロックが5秒以上後に到着したブロックを追跡します。",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_lateblocks_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "最新ステーク",
   "type": "stat",
   "description": "単位：₳（ADA）",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "op_cert_counter", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "uql",
     "uql": "parse-json | project \"live_stake\"=div(\"live_stake\",1000000)",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "有効ステーク",
   "type": "stat",
   "description": "単位：₳（ADA）",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "op_cert_counter", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "uql",
     "uql": "parse-json | project \"active_stake\"=div(\"active_stake\",1000000)",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "最新の委任者数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "live_delegators", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "最新の飽和状態",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "live_saturation", "text": "", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.koios.rest/api/v1/pool_info",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"_pool_bech32_ids\":[\"bech32_id_of_your_pool\"]}",
      "headers": [
       { "key": "Accept", "value": "application/json" },
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "ブロック受信までの時間",
   "type": "stat",
   "description": "■ブロック受信までの時間：ブロックがミントされるべきだった時から、ローカルのリレーがブロックを受信するまでの遅延を推定した時間。この指標には、コンセンサス/元帳がそのブロックを採用するまでの時間は含まれていません（採用されない可能性もあります）",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_real",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ピア",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_ActivePeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "P2P着信( In )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_inboundConns_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "P2P発信 ( Out )",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_outboundConns_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "起動時間",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / 1000", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "スロット",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU使用量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg without(cpu, mode)(irate(node_cpu_seconds_total{job=\"prometheus\", mode=\"idle\"}[1m]))",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ブロック",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "最新のブロック数",
   "type": "stat",
   "description": "■リレーノードの有用性判定：人気のないノードには0に近い値が与えられ、非常に有用なノードには1以上の値が与えられます。\n値が0の場合、誰もあなたのリレーからブロックを取得していないことを意味します。\n値が1の場合、新しいブロックが作成されるたびに、誰かがそれを取得していることを意味します。\n値が2以上の場合は、ミントされたブロックごとに、2つのノードがあなたからそのブロックをフェッチしていることを意味します。",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_served_block_latest_int[1h])/rate(cardano_node_metrics_blockNum_int[1h])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ノードメモリ使用量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rts_gc_current_bytes_used", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "システムメモリ使用量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "スワップメモリ使用量",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "フォーク",
   "type": "stat",
   "description": "■チェーン上のフォーク数をカウント：ノードがスタートしてからのフォーク数。ブロック伝播遅延の影響で2秒前後のスロット間のスケジュールで発生",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_forks_counter",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ディスク使用率",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ピア ホット",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_Hot_int",
     "legendFormat": "{{alias}} - Hot"
    }
   ]
  },
  {
   "title": "ピア ウォーム",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_Warm_int",
     "legendFormat": "{{alias}} - Warm"
    }
   ]
  },
  {
   "title": "ピア コールド",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_Cold_int",
     "legendFormat": "{{alias}} - Cold"
    }
   ]
  },
  {
   "title": "ノードタイムエラー最大秒数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds * 1000",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "チェーン密度",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "スロットミス数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "ネットワーク使用量",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "ディスク使用量",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  }
 ]
}